_wandb:
    value:
        cli_version: 0.18.6
        m: []
        python_version: 3.10.7
        t:
            "1":
                - 1
                - 55
            "2":
                - 1
                - 55
            "3":
                - 16
                - 23
                - 55
            "4": 3.10.7
            "5": 0.18.6
            "8":
                - 5
            "12": 0.18.6
            "13": darwin-arm64
algorithm:
    value: PPO
n_envs:
    value: 4
total_timesteps:
    value: 1000000
